---
version: '3'
services:
  prometheus:
    restart: always
    image: prom/prometheus:v2.26.0
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules.yml:/etc/prometheus/rules.yml
    expose:
      - "9090"
    ports:
      - 9090:9090

  alertmanager:
    restart: always
    depends_on:
      - prometheus
    image: prom/alertmanager:v0.21.0
    container_name: alertmanager
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    expose:
      - "9093"
    ports:
      - 9093:9093
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui